### ISSUE TITLE
CSPM trivially vulnerable to SQL injection

### ISSUE THREAD

**Issue by bmenrigh** [rkhous/CSPM#1]
The DB queries / inserts just use simple string concatenation and introduce SQL injection vulnerabilities.  For example:
`cursor.execute("SELECT id FROM forts WHERE NAME LIKE '" + str(arg) + "%';")` 

You should consider moving to parameterized queries.  See https://stackoverflow.com/questions/775296/python-mysql-parameterized-queries for some examples of how to do this.

**Comment by rkhous** [comment]
switched over to parameterized queries.
