### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by Nightfirez1988** [rkhous/CSPM#3]
i cant get the map run because i get this error
async def raid(ctx, arg, arg2, arg3, arg4):#arg = gym name, arg2 = pokemon name, arg3 = level, arg4 = time remaining
        ^
SyntaxError: invalid syntax****
i looked at the code and i found nothing pls help

**Comment by rkhous** [comment]
did you change anything?
Is there more to the error?

**Comment by rkhous** [comment]
This is programmed in Python 3. 
You are likely using Python 2. 
Please download Python 3 from https://www.python.org/download/releases/3.0/
