### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by Nightfirez1988** [rkhous/CSPM#6]
PS C:\Users\MasterChief\Desktop\CSPM-master> python --version
Python 3.4.3
PS C:\Users\MasterChief\Desktop\CSPM-master> python cspm.py
  File "cspm.py", line 54
    async def raid(ctx, arg, arg2, arg3, arg4): arg = gym name, arg2 = pokemon name, arg3 = level, arg4 = time remaining
        ^
SyntaxError: invalid syntax
i have completly new install all.
But i get this error i havent modiefy any docs.
pls help me

**Comment by rkhous** [comment]
You removed a #, making a comment not a comment. You edited the code, this is not an issue with my bot.

**Comment by Nightfirez1988** [comment]
PS C:\Users\MasterChief\Desktop\CSPM-master> python cspm.cy
C:\Python30\python.exe: can't open file 'cspm.cy': [Errno 2] No such file or directory
PS C:\Users\MasterChief\Desktop\CSPM-master> python cspm.py
  File "cspm.py", line 54
    async def raid(ctx, arg, arg2, arg3, arg4):  # arg = gym name, arg2 = pokemon name, arg3 = level, arg4 = time remaining
        ^
SyntaxError: invalid syntax

so completly fresh install -.-
