### ISSUE TITLE
Pokemon dont show on map !

### ISSUE THREAD

**Issue by m3g4mInD** [rkhous/CSPM#8]
Hi, and thanks for this great tool,
i have managed to work with cspm but the problem is, after add  1 pokemon if i add a 2 one he doesnt show on map only the first one ,but the 2one coords  is on db.

**Comment by m3g4mInD** [comment]
I use .spawn dragonite 48.861715 2.339613, agter some seconds i add  .spawn larvitar 48.800371 2.297107 its show on db but dont show on map the 2 one.  I'am using hydro fork monocle.
 @rkhous

**Comment by rkhous** [comment]
I'm on Hydro's fork as well, so that shouldn't be a problem. It says blank even when the page is refreshed? Have you tried other Pokemon? 

Also:
1) Is the bot telling you the query was successful? 
2) any error messages? 
3) are you on the latest version of CSPM?

**Comment by m3g4mInD** [comment]
After add ratata or charmander dont show on pmsf, i have check  all if i have some hidde pokemons and nothing.I 'am using pmsf with a new pr, i gonna minstall a default one and see what happends.

**Comment by rkhous** [comment]
oh okay, I didn't notice you were using PMSF. 
I haven't tested this on PMSF, just web.py

**Comment by m3g4mInD** [comment]
Even with the default pmsf still same weird error, now time to see if web.py works
Thanks @rkhous
